### ISSUE TITLE
Reinstate process that removes NULL values from occurrence records

### ISSUE THREAD

**Issue by acvaughan** [AtlasOfLivingAustralia/data-management#74] opened 2015-03-13 01:13 UTC
Natasha had created a process that automatically removed obsolete values from occurrence records (for each record provided in the delta, it removed columns that don't have data supplied). This has not been working for some time, but is a crucial process to ensure the currency and accuracy of AVH data.

This is also desired by the faunal collections community.

VERY HIGH PRIORITY!

**Comment by nielsklazenga** [comment] 2015-07-24 04:37
This was identified by both FCIG and HISCOM as the number 1 data quality issue for OZCAM and AVH. Could it please be given the priority it deserves (i.e. the priority Alison assigned to it above)?

The issue is that if you deliver a NULL value for a field for which there is already a value in the existing BioCache record, the old value stays in the record. This is a problem, for example, when there is a new Identification and the old Identification had `identificationRemarks`, but the new one doesn't, or, in AVH, for loans that have been returned. Also, sometimes, the wrong data is delivered and sometimes, believe it or not, there are data processing errors that put the wrong data in the wrong place. In order to effectively update records or correct errors in records in AVH and OZCAM – and any other managed data set – we need to have the ability to reset values to NULL.

I think the process that Natasha put in place, or was ready to put in place (I have seen it work) would simply remove the field from a record if a NULL value (an empty cell in a Darwin Core Archive) was delivered. It was independent from the aggregation process, so you can choose for which data sets to use it and for which not.

**Comment by AlexisTindall** [comment] 2015-07-30 03:02
Thanks for this comment Niels. He is correct, this was a very high priority for the faunal collections community as well.

**Closed** 2016-06-09 05:41 UTC
Labels: Data Quality, Infrastructure
