### ISSUE TITLE
TMAG invertebrates collection update

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#937] opened 2023-07-06 04:37 UTC
- [x] `dr1840` (Tasmanian Museum and Art Gallery provider for OZCAM-Arthropoda) deleted from databox
- [x] `dr1840` is set to private in prod
- [x] `dr1840` is set not to be shared with GBIF
- [x] metadata is updated on GBIF to move citations on this DR to `dr347`
- [x] records and dataset are deleted for `dr1840`

**Comment by rosemaryjoconnor** [comment] 2024-09-26 07:56
**26/09/2024**

**dr1840** - no longer exists in either databox or production. Downloaded an old backup to get some sample records. 

**GBIF**

- dr1840: https://www.gbif.org/dataset/f7d6a733-fa5e-43ba-b06e-e70778953ead
- dr347:  https://www.gbif.org/dataset/4ffe66a0-6c8b-11de-8226-b8a03c50a862

**To Do:**

- Determine who to email re the metadata update

**Comment by peggynewman** [comment] 2024-10-21 02:15
I've tried this in the UAT environment and it seems to have worked:

1. Login to the registry
2. Find the [old dataset](https://registry.gbif.org/dataset/f7d6a733-fa5e-43ba-b06e-e70778953ead)
3. Click ‘edit’
4. In the ‘Duplicate of Dataset’ line, add the UUID of the new dataset: 4ffe66a0-6c8b-11de-8226-b8a03c50a862
5. Click ‘Save’
6. In the three dots in the top right corner, click ‘delete dataset’.
7. Confirm

... waiting to see if the replacement text appears shortly with a reindex or something.

**Comment by peggynewman** [comment] 2024-10-21 03:25
All done in gbif test and prod

**Closed by peggynewman** 2024-10-21 03:25 UTC
