### ISSUE TITLE
Yugul Mangi occurrence data load

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#718] opened 2021-08-23 06:50 UTC
Ask Peggy for emails containing data and metadata.

**Comment by sadeghim** [comment] 2021-08-24 00:25
DR is created: https://collections.ala.org.au/public/show/dr17780

**Comment by sadeghim** [comment] 2021-08-30 03:03
Lat and Lon were swapped. Fixed and re-ingested. Waiting for the indexing tomorrow.

**Comment by peggynewman** [comment] 2021-08-31 08:06
There are still 2 records with spatial issues. 
![image](https://user-images.githubusercontent.com/1271932/131466252-f8bf90cf-3541-4b6b-af54-d9efe10dadc5.png)

**Comment by sadeghim** [comment] 2021-09-01 23:13
The issue is fixed now. There was an issue with the coordinates in the original data:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/1578598/131757352-902fac6d-0827-407e-859b-20f1ae0238ca.png">

**Closed by sadeghim** 2021-09-01 23:13 UTC
Labels: Data Load
